[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "notswayze"
authors = [{name = "NotSwayze", email = "notswayzegaming@gmail.com"}]
dynamic = ["version", "description"]
